version: "1.0"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: mydb
      MYSQL_USER: cmnUser
      MYSQL_PASSWORD: spring1234

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot1234"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build:
      context: ./back
      dockerfile: Dockerfile

    container_name: backend-container

    restart: unless-stopped

    ports:
      - "8080:8080"

    depends_on:
      mysql:
        condition: service_healthy

    # environment:
    #   SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydb?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    #   SPRING_DATASOURCE_USERNAME: cmnUser
    #   SPRING_DATASOURCE_PASSWORD: spring1234

  web:
    build:
      context: ./front
      dockerfile: Dockerfile

    container_name: frontend-container

    ports:
      - "80:80"

    restart: unless-stopped

volumes:
  mysql-data: