# version: "1.0"

services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile

    container_name: mysql-container
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-time-zone=+09:00

    restart: unless-stopped

    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: mydb
      MYSQL_USER: cmnUser
      MYSQL_PASSWORD: spring1234

    # ports:
    #   - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql-files:/docker-entrypoint-initdb.d
      - ./mysql/char.cnf:/etc/mysql/conf.d/char.cnf:ro

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot1234"]
      interval: 10s
      timeout: 5s
      retries: 10

    networks:
      - webnet


  app:
    build:
      context: ./back
      dockerfile: Dockerfile

    container_name: backend-container

    restart: unless-stopped

    ports:
      - "8080:8080"
    # expose:
      # - "8080"

    depends_on:
      mysql:
        condition: service_healthy

    volumes:
      - ./data/images:/app/images

    networks:
      - webnet

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    #   SPRING_DATASOURCE_USERNAME: cmnUser
    #   SPRING_DATASOURCE_PASSWORD: spring1234

  web:
    build:
      context: ./front
      dockerfile: Dockerfile

    container_name: frontend-container

    ports:
      - "80:80"

    depends_on:
      - app

    restart: unless-stopped

    networks:
      - webnet

volumes:
  mysql-data:

networks:
  webnet:
    driver: bridge