version: "3.9"

services:
  mysql:
    image: mysql:8.4
    container_name: mysql

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: mydb
      MYSQL_USER: spring
      MYSQL_PASSWORD: spring1234

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot1234"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: springboot

    restart: unless-stopped

    ports:
      - "8080:8080"

    depends_on:
      mysql:
        condition: service_healthy

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/board?serverTimezone=UTC&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: spring
      SPRING_DATASOURCE_PASSWORD: spring1234

volumes:
  mysql-data: